#
# Copyright 2020 Confluent Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
FROM confluentinc/cp-server-connect:7.4.1

ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components"

RUN confluent-hub install --no-prompt mongodb/kafka-connect-mongodb:1.11.1 \
    && confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.2.5

COPY ./mysql-connector-java-8.0.25.jar /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/lib

#USER root
#RUN mkdir -p /usr/share/java/kafka
#RUN wget -P  /usr/share/java/kafka https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.12.0/jmx_prometheus_javaagent-0.12.0.jar; \
#    wget -P  /usr/share/java/kafka https://github.com/confluentinc/jmx-monitoring-stacks/blob/main/shared-assets/jmx-exporter/kafka_connect.yml;

# Add the JMX exporter Java agent
#ADD jmx_prometheus_javaagent-0.15.0.jar /opt/prometheus/
#ADD kafka_connect.yml /opt/prometheus/

#ENV CONNECT_JMX_OPTS="-javaagent:/opt/prometheus/jmx_prometheus_javaagent-0.15.0.jar=9404:/opt/prometheus/kafka_connect.yml"
#ENV KAFKA_OPTS="-javaagent:/usr/share/java/kafka/jmx_prometheus_javaagent-0.12.0.jar=9404:/usr/share/java/kafka/kafka_connect.yml"


#EXPOSE 9404
#RUN curl -k -SL "https://downloads.mysql.com/archives/get/p/3/file/mysql-connector-java-8.0.25-1.el8.noarch.rpm" \
#     | tar -xzf - -C /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/lib \
#     --strip-components=1 mysql-connector-java-5.1.39/mysql-connector-java-${MYSQL_DRIVER_VERSION}-bin.jar

