apiVersion: v1
kind: Service
metadata:
  name: hms
  namespace: flink  
spec:
  selector:
    app: hms
  ports:
    - protocol: TCP
      port: 9083
      targetPort: 9083
  type: ClusterIP # Use LoadBalancer if external access is required
