apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvminio
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/tmp
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - my-kind-cluster-east-control-plane
                - my-kind-cluster-east-worker
                - my-kind-cluster-east-worker2  
